Задание — Список покупок
shveetsov/surf-course pull request #11
Opened 2024-03-10 02:27 UTC by shveetsov

2024-03-10 02:34 UTC, shveetsov commented
https://github.com/shveetsov/surf-course/assets/101689169/1a124cd7-43ca-4c82-988d-e836f6acdcbe

2024-03-11 15:56 UTC, Evgenia-bit requested changes
Пожалуйста, в следующий раз создавайте проект только для ios и android.
В будущем, если приложение не слишком маленькое, старайтесь не складывать весь код в main. Разбивайте проект на части.
И хорошо бы сразу писать документацию к классам и методам

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +  "none": "Без сортировки",
лучше добавить прямо в enum SortType переменную с текстом и не создавать отдельную Map. Здесь описано как это можно сделать https://codewithandrea.com/tips/dart-2.17-enums-with-members/

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +  "none": "Без сортировки",
и строки желательно вынести в константы. Пример:
```dart
/// Строковые константы приложения
class AppStrings {
  static const noneSortTypeName = 'Без сортировки';
}
```

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +Widget listProductsCategory(
сделайте виджеты вместо методов

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +  Widget radioListTile(String title, dynamic sortValue) {
здесь тоже лучше сделать отдельный виджет

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +    for (var product in widget.productList) {
выносите такие вычисления в методы

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +          '${(processNumber(product.price * (product.sale / 100) / 100))} руб',
выносите такие сложные вычисления в переменные

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +      model.Category.all: [...dataForStudents]
можно просто model.Category.all: dataForStudents

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +            iconTitle('assets/icons/article.svg', 'Каталог',
выносите такое в константы. Пример:
```dart
class AppAssets {
  static const favorite = 'res/icons/heart_icon.svg';
}
```

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +                        switch (selectedSortType) {
выносите такие большие куски логики из верстки в отдельные методы

2024-03-11 15:56 UTC, Evgenia-bit commented on task-11/lib/main.dart
> +SortType selectedSortType = SortType.none;
Не желательно хранить состояние приложения в глобальных переменных. Лучше переместите их в стейт виджета

2024-03-12 09:37 UTC, merged