Задание — Валидация форм
shveetsov/surf-course pull request #16
Opened 2024-03-26 08:54 UTC by shveetsov

2024-03-26 08:57 UTC, shveetsov commented
https://github.com/shveetsov/surf-course/assets/101689169/f908a9a3-4e26-4d21-b855-4044faffd1d6

2024-03-26 13:57 UTC, Evgenia-bit requested changes
Валидация должна происходить, когда поле теряет фокус ввода. У вас она происходит сразу. Посмотрите в сторону виджета FocusNode. Пример реализации можете посмотреть здесь https://github.com/flutter/flutter/issues/44921.

2024-03-26 13:57 UTC, Evgenia-bit commented on task-16/lib/main.dart
> +class ListAnimal extends StatelessWidget {
Пишите документацию сразу ко всем классам и методам

2024-03-26 13:57 UTC, Evgenia-bit commented on task-16/lib/main.dart
> +      required this.sendForm});
Форматируйте код с помощью запятых. Здесь можно нужно запятую после required this.sendForm. Аналогично в похожих местах

2024-03-26 13:57 UTC, Evgenia-bit commented on task-16/lib/main.dart
> +    bool check = false;
Старайтесь упрощать конструкции. Здесь можно написать просто:
```dart
final check = animal == currentAnimal;
```

2024-03-26 13:57 UTC, Evgenia-bit commented on task-16/lib/main.dart
> +  buildMaterialDatePicker(BuildContext context) async {
Обязательно пишите возвращаемые типы у методов, иначе они устанавливаются как dynamic. Это приводит к неожиданным ошибкам во время выполнения программы

2024-03-31 03:05 UTC, shveetsov commented
https://github.com/shveetsov/surf-course/assets/101689169/ef613811-449c-4e49-bb46-51764f141480

2024-04-02 05:37 UTC, merged